
all : clean

reset:
	@reset


clean:
	@echo "cleaning project folder.."
	@find . -name '*.out' -delete
	@echo "deleted out files"
	@find . -name '*.exe' -delete
	@echo "deleted exe files"
	@find . -name '*.vcd' -delete
	@echo "deleted vcd files"
	@find . -name '*.zip' -delete
	@echo "deleted zip files"
