good_run: clrscr compile   
	@./main.out

bad_run:
	./main.out
	
compile:
	@g++ main.cpp -o main.out

clrscr:
	clear

clean:
	@rm *.out
	
#	@ (rm -q *.out  && echo "done" ) || echo "nothing to clean"
	